# https://fabricmc.net/develop
org.gradle.jvmargs=-Xmx1G

minecraft_version=26.3-snapshot-10
minecraft_compat_version=26.3.x

loader_version=0.19.3
loom_version=1.15-SNAPSHOT

# Mod Properties
mod_version=1.2.4+26.3
maven_group=dev.doublekekse
archives_base_name=area_tools

# Dependencies
fabric_api_version=0.158.3+26.3
